wordpressdb:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=tastamam
    - MYSQL_DATABASE=wpdatabase
  expose:
    - "3306"

wordpress:
  build: components/wordpress
  environment:
    - WORDPRESS_DB_PASSWORD=tastamam
  links:
    - wordpressdb:mysql
  ports:
    - 8080:80

