mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=tastamam
  expose:
    - "3306"

wordpress:
  build: components/wordpress
  environment:
    - WORDPRESS_DB_PASSWORD=tastamam
  links:
    - mysql
  ports:
    - 8080:80

